create extension if not exists pgcrypto;

create table public.pilot_applications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  last_contact_at timestamptz,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) between 5 and 254 and email = lower(email)),
  whatsapp text check (whatsapp is null or char_length(whatsapp) between 8 and 32),
  community_name text not null check (char_length(community_name) between 2 and 160),
  member_range text not null check (member_range in ('up_to_50', '51_to_200', '201_to_500', 'more_than_500')),
  applicant_role text not null check (applicant_role in ('owner', 'administrator', 'moderator', 'member', 'other')),
  goals text not null check (char_length(goals) between 20 and 2000),
  privacy_notice_version text not null,
  privacy_notice_acknowledged_at timestamptz not null,
  contact_requested_at timestamptz not null,
  source text not null default 'resuma.ia.br' check (char_length(source) <= 120),
  status text not null default 'new' check (status in ('new', 'reviewing', 'contacted', 'selected', 'declined', 'deleted')),
  submission_fingerprint text not null check (char_length(submission_fingerprint) = 64)
);

create unique index pilot_applications_fingerprint_community_idx
  on public.pilot_applications (submission_fingerprint, lower(community_name));
create index pilot_applications_status_created_idx
  on public.pilot_applications (status, created_at desc);

alter table public.pilot_applications enable row level security;
revoke all on table public.pilot_applications from anon, authenticated;
grant select, insert, update, delete on table public.pilot_applications to service_role;

create table public.privacy_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text not null check (char_length(email) between 5 and 254 and email = lower(email)),
  request_type text not null check (request_type in ('confirmation', 'access', 'correction', 'deletion', 'revocation', 'information', 'other')),
  details text not null check (char_length(details) between 10 and 2000),
  privacy_notice_version text not null,
  status text not null default 'new' check (status in ('new', 'verifying_identity', 'processing', 'completed', 'rejected')),
  submission_fingerprint text not null check (char_length(submission_fingerprint) = 64)
);

create index privacy_requests_status_created_idx
  on public.privacy_requests (status, created_at desc);

alter table public.privacy_requests enable row level security;
revoke all on table public.privacy_requests from anon, authenticated;
grant select, insert, update, delete on table public.privacy_requests to service_role;

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_date date not null default current_date,
  anonymous_session_id text not null check (char_length(anonymous_session_id) = 36),
  event_name text not null check (event_name in ('page_view', 'pilot_cta', 'pilot_submit')),
  path text not null check (char_length(path) between 1 and 300),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 253),
  device_class text not null check (device_class in ('desktop', 'mobile', 'tablet')),
  consent_version text not null
);

create unique index analytics_events_daily_unique_idx
  on public.analytics_events (event_date, anonymous_session_id, event_name, path);
create index analytics_events_created_idx
  on public.analytics_events (created_at desc);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;
grant select, insert, delete on table public.analytics_events to service_role;

comment on table public.pilot_applications is 'Manually reviewed applications for the Resuma pilot. No automated outreach.';
comment on table public.privacy_requests is 'LGPD data-subject requests submitted through the Resuma privacy page.';
comment on table public.analytics_events is 'First-party, consent-gated, pseudonymous website events retained for at most 90 days.';
